In [260]:
import numpy as np

In [261]:
np.__version__

'2.3.5'

## Creating array

In [262]:
a = np.array([1,2,3,4])

In [263]:
type(a)

numpy.ndarray

In [264]:
a

array([1, 2, 3, 4])

In [6]:
a.dtype   # data type of elements 

dtype('int64')

In [7]:
a.shape

(4,)

In [265]:
langs = np.array(("Java","Python","C","JavaScript"))

In [266]:
langs

array(['Java', 'Python', 'C', 'JavaScript'], dtype='<U10')

In [10]:
a = np.array((1,2,'abc')) 

In [11]:
a

array(['1', '2', 'abc'], dtype='<U21')

#### Difference between Array and list

In [267]:
a = np.array((1,4,6,8,9))
a * 2  # Multiplication 

array([ 2,  8, 12, 16, 18])

In [268]:
a * a

array([ 1, 16, 36, 64, 81])

In [14]:
a + a

array([ 2,  8, 12, 16, 18])

In [269]:
## Python list with * 
pa = [1,4,6,8,9]
pa * 2     # Replication 

[1, 4, 6, 8, 9, 1, 4, 6, 8, 9]

In [270]:
pa + pa     # Concatenation 

[1, 4, 6, 8, 9, 1, 4, 6, 8, 9]

### arange()

In [271]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
a.dtype

dtype('int64')

In [272]:
a = np.arange(1, 20, 2, dtype='int16')
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int16)

#### Other functions to create array 

In [20]:
a = np.full(10, 5)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [274]:
a = np.full((5, 5), 3)  # Array of 5 X 5 and fill it with 3
a

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [275]:
a.dtype

dtype('int64')

In [276]:
a = np.ones(10)
a, a.dtype

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), dtype('float64'))

In [278]:
a = np.ones(10, dtype = np.int32)
a, a.dtype

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32), dtype('int32'))

In [279]:
a[0] = 100    # modify element

In [280]:
a

array([100,   1,   1,   1,   1,   1,   1,   1,   1,   1], dtype=int32)

In [26]:
# a[0] = 'Abc' # Not possible as array are homegeneous 

In [27]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [281]:
a = np.eye(5,5)   # Identity matrix
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Random numbers generation

In [283]:
a = np.random.rand(10)
a

array([0.31577671, 0.21240548, 0.93757088, 0.86198354, 0.66858309,
       0.99920931, 0.78509461, 0.52343355, 0.81387066, 0.3212001 ])

In [284]:
a[-1]

np.float64(0.3212001016551309)

In [285]:
for n in a[:5]:
    print(n)

0.3157767127218125
0.2124054849776119
0.9375708783421705
0.8619835382141836
0.668583093707584


In [32]:
a = np.random.randint(1,100,10)   # min, max, size of array 
a

array([ 9, 27, 97, 71, 35, 71, 60, 32, 72, 78], dtype=int32)

In [286]:
a = np.random.randint(1,10,(3,3))
a

array([[5, 4, 2],
       [6, 5, 6],
       [2, 3, 2]], dtype=int32)

### linspace()

In [34]:
a = np.linspace(1,10,5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [287]:
a, step = np.linspace(1,20,5, retstep = True)  # Return Step value 

In [288]:
a, step 

(array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ]), np.float64(4.75))

In [289]:
a, step = np.linspace(1,10,5, dtype=np.int32, retstep=True)
a, step

(array([ 1,  3,  5,  7, 10], dtype=int32), np.float64(2.25))

### Attributes of ndarray

In [290]:
a = np.random.randint(1,10,(3,3))

In [291]:
a

array([[2, 9, 5],
       [5, 5, 2],
       [4, 7, 3]], dtype=int32)

In [292]:
a.ndim, a.size, a.dtype, a.shape

(2, 9, dtype('int32'), (3, 3))

### Indexing and slicing

In [293]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [294]:
a[0,0], a[4,0]

(np.int64(1), np.int64(21))

In [43]:
# Nested list in Python
l = [[1,2,3], [10,20,30,40]]
l[1][0]

10

In [295]:
a[4]  # Single row 

array([21, 22, 23, 24, 25])

In [45]:
a[-1,-1]   # Last row , last col 

np.int64(25)

In [46]:
a[-1]   # Last row 

array([21, 22, 23, 24, 25])

In [297]:
a[-1,0], a[0][-1] , a[0, -1]

(np.int64(21), np.int64(5), np.int64(5))

### slicing

In [298]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
a[1:3]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [50]:
a[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [51]:
a[:,2]  # Column with index 2 

array([ 3,  8, 13, 18, 23])

In [52]:
a[4,3:]

array([24, 25])

In [53]:
b = a[:,-1]   # Last column 
b.shape, b

((5,), array([ 5, 10, 15, 20, 25]))

In [54]:
b = a[:,-1:]   # Last column 
b.shape, b

((5, 1),
 array([[ 5],
        [10],
        [15],
        [20],
        [25]]))

In [55]:
a[-2:,-2:]

array([[19, 20],
       [24, 25]])

In [56]:
# a[5,5]  --> Error 

In [57]:
a[::2]   # Alternate rows 

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [58]:
a[::-1]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [59]:
a[::-1, ::-1]

array([[25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [60]:
a[:,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21]])

In [61]:
a[-2:, ::-1] # Last two rows and cols in reverse 

array([[20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21]])

In [62]:
a[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [63]:
# Last two col and alternate rows 
a[::2, -2:]

array([[ 4,  5],
       [14, 15],
       [24, 25]])

In [64]:
# Last two colunms in reverse order 
a[:,:-3:-1]

array([[ 5,  4],
       [10,  9],
       [15, 14],
       [20, 19],
       [25, 24]])

### Index by array

In [299]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
a[[3,6,9]]    # index is an array

array([ 4,  7, 10])

In [67]:
# Can we do it in Python list 
#l = [1,2,3,4]
#print( l[[1,3]])

In [300]:
a[[-1,-5,0]]

array([10,  6,  1])

In [301]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [303]:
a [[0,2],[1,3]]

array([ 2, 14])

In [305]:
#a[[0,2],[1,3,4]]   # Error 

In [306]:
a [[1,2,3],[4,4,-1]]

array([10, 15, 20])

### Iterate 

In [307]:
a = np.arange(10)
for n in a:
    print(n, end = ' ')

0 1 2 3 4 5 6 7 8 9 

In [308]:
a = np.random.randint(1,10,(3,3))
a

array([[5, 2, 4],
       [4, 9, 6],
       [3, 2, 6]], dtype=int32)

In [309]:
for r in a:
    for c in r:
         if c % 2 == 0:
                print(c, end = ' ')

2 4 4 6 2 6 

### Boolean Indexing

In [310]:
a = np.random.randint(1,100,5)
a

array([50, 57, 40, 24, 18], dtype=int32)

In [311]:
a [ [True,False,True,False, False]]

array([50, 40], dtype=int32)

In [313]:
a

array([50, 57, 40, 24, 18], dtype=int32)

In [314]:
a % 2 == 0 

array([ True, False,  True,  True,  True])

In [315]:
a [ a % 2 == 0]

array([50, 40, 24, 18], dtype=int32)

In [316]:
a > 50

array([False,  True, False, False, False])

In [82]:
# a [[True,True]]     --> Not valid because array of booleans and indexed array are not of same size

In [318]:
a = np.random.randint(1,100,10)
a

array([92, 86, 77,  4, 97,  8,  1, 56, 58,  6], dtype=int32)

In [319]:
evens = a % 2 == 0 
evens

array([ True,  True, False,  True, False,  True, False,  True,  True,
        True])

In [320]:
a [evens]    # a [ a % 2 == 0 ]

array([92, 86,  4,  8, 56, 58,  6], dtype=int32)

In [321]:
a[a % 2 == 1]  # Boolean Indexing

array([77, 97,  1], dtype=int32)

In [87]:
a2 = a [ a > 50]

In [88]:
a2

array([68, 93], dtype=int32)

In [322]:
a = np.random.randint(1,10, (5,5))
a

array([[8, 6, 8, 2, 1],
       [3, 7, 4, 6, 5],
       [2, 4, 7, 6, 4],
       [2, 3, 5, 5, 8],
       [9, 8, 2, 4, 5]], dtype=int32)

In [90]:
a > 5

array([[False, False, False,  True, False],
       [False,  True,  True,  True, False],
       [False, False,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True, False]])

In [323]:
a [ a > 5 ] 

array([8, 6, 8, 7, 6, 7, 6, 8, 9, 8], dtype=int32)

#### Masking

In [92]:
(a > 2) & (a < 8)

array([[ True, False, False, False,  True],
       [ True, False,  True, False,  True],
       [False, False, False,  True,  True],
       [False, False,  True, False,  True],
       [ True,  True,  True, False,  True]])

In [93]:
a [ (a > 2) & (a < 8)]  # Anding 

array([4, 3, 4, 6, 4, 6, 5, 7, 6, 6, 6, 5, 4], dtype=int32)

In [325]:
#a [(a > 2) and (a < 8)]  # Anding in python 

In [326]:
a = np.random.randint(1,10,10)
a

array([4, 4, 4, 6, 7, 4, 9, 7, 9, 5], dtype=int32)

In [327]:
ba1 = a >= 1
print(ba1)
ba2 = a <= 5
print(ba2)

[ True  True  True  True  True  True  True  True  True  True]
[ True  True  True False False  True False False False  True]


In [328]:
ba1 | ba2    # Oring 

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [98]:
a [ba1 & ba2]

array([5, 5, 2, 2, 4, 5], dtype=int32)

In [330]:
def isprime(n):
    for i in range(2, n//2 + 1):
        if n % i == 0 :
               return False
            
    return True

In [331]:
# Returns a list of booleans 
def prime(a):
    lst = []
    for n in a:
         lst.append(isprime(n))   # Append true or false 
        
    return lst  # List of booleans 

In [340]:
# Returns a list of booleans 
def prime_booleans(a):
    return [isprime(n) for n in a]

In [336]:
a = np.random.randint(1,100,10)
a

array([70, 37,  6, 29, 40, 94, 50, 85, 32, 31], dtype=int32)

In [337]:
print(prime(a))

[False, True, False, True, False, False, False, False, False, True]


In [338]:
a[prime(a)]

array([37, 29, 31], dtype=int32)

In [341]:
prime_booleans(a)

[False, True, False, True, False, False, False, False, False, True]

In [342]:
a[prime_booleans(a)]  

array([37, 29, 31], dtype=int32)

In [107]:
## Iterate array a and display all prime numbers 

### Array Operations

In [343]:
a = np.array([1,2,3,4,5])

In [344]:
b = a + 10.5

In [345]:
b, b.dtype, a.dtype

(array([11.5, 12.5, 13.5, 14.5, 15.5]), dtype('float64'), dtype('int64'))

In [346]:
print(b)
b -= 5        # inplace  b = b - 5
print(b)

[11.5 12.5 13.5 14.5 15.5]
[ 6.5  7.5  8.5  9.5 10.5]


In [112]:
# Diff sizes for array 
a1 = np.arange(4)
a2 = np.arange(5)
#a1 + a2    # Error

In [347]:
a1 = np.arange(5)
a2 = np.arange(5)
a1 == a2    

array([ True,  True,  True,  True,  True])

#### all() vs. any()

In [349]:
ba = np.array([True,False,True])
print(ba.all())
print(ba.any())

False
True


In [350]:
a1 == a2 

array([ True,  True,  True,  True,  True])

In [351]:
(a1 == a2).all()   # True if all elements are equal 

np.True_

In [352]:
(a1 == a2).any() 

np.True_

In [353]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([1,4,3,2,4])

In [354]:
(a1 > a2).any() 

np.True_

In [355]:
# Do we have any even number in the array
a = np.random.randint(1,100,10)
print(a)
evens = a % 2 == 0 
print(evens)
print(evens.any())

[36 37 78 31  7 53 33 41  1 47]
[ True False  True False False False False False False False]
True


### Methods of ndarray

In [357]:
a = np.random.randint(1,100,10)
print(a)
b = np.zeros(5)
print(b)

[17 55  3  4 91 91 78 66  2 30]
[0. 0. 0. 0. 0.]


In [358]:
a.sum()

np.int64(437)

In [123]:
a.any()  # Is there any true value (0 is false, non-zero is true)

np.True_

In [124]:
b.any()

np.False_

In [125]:
a.all()   # Are all true

np.True_

In [360]:
## No.of odd numbers in each row 
a = np.random.randint(1,100,(6,6))
print(a)
for idx, row in enumerate(a):
    print(idx,(row % 2 == 1).sum())

[[14 30 10 53 24 90]
 [94 47 40 29  9 32]
 [12 33  5 58 54 34]
 [66 90 81 62 11 71]
 [77 90 87 85  7 82]
 [ 5 86 45 95  4 77]]
0 1
1 3
2 2
3 3
4 4
5 4


In [127]:
np.array([True,False,True]).sum()   # True means 1, False means 0 

np.int64(2)

In [361]:
## How many subjects student passed
marks = np.random.randint(1,100,(6,6))
print(marks)
for row in marks:
    #print(row >= 50)
    print((row >= 50).sum())

[[63 48 32 45 89 83]
 [32 31 53 42 86 83]
 [84 20 94 48 37 29]
 [20 25 94 50 25  9]
 [20 46 46 34 27 89]
 [95 90 89 11 67 73]]
3
3
2
2
1
5


In [362]:
marks.mean()  # Total mean for entire array 

np.float64(53.02777777777778)

In [363]:
for row in marks:
    print(int(row.mean()))   #  Mean for each student 

60
54
52
37
43
70


In [131]:
marks >= 50

array([[False,  True,  True,  True,  True,  True],
       [ True, False, False,  True, False,  True],
       [ True,  True, False,  True, False, False],
       [False, False, False, False, False,  True],
       [ True, False,  True, False,  True, False],
       [ True,  True, False,  True, False, False]])

In [364]:
(marks >= 50).sum()  # total no. of students passed

np.int64(16)

#### Using axis parameter

In [365]:
marks = np.random.randint(1,100,(3,3))

In [366]:
marks

array([[24, 33, 27],
       [75, 43, 17],
       [28, 93, 62]], dtype=int32)

In [367]:
marks.sum()

np.int64(402)

In [368]:
marks.sum(axis=0) # Column-wise total 

array([127, 169, 106])

In [369]:
marks.sum(axis=1) # Row-wise total 

array([ 84, 135, 183])

In [370]:
(marks >= 50).sum(axis=0)  # Column-wise Sum (Subject)

array([1, 1, 1])

In [371]:
(marks >= 50).sum(axis=1)  # row-wise Sum (Student wise)

array([0, 1, 2])

In [372]:
marks.sum(axis = 1) # total marks for each student

array([ 84, 135, 183])

In [373]:
marks.mean(axis=1)

array([28., 45., 61.])

In [374]:
marks.mean(axis=1).max()

np.float64(61.0)

In [375]:
# higest marks for each student
marks.max(axis = 1)

array([33, 75, 93], dtype=int32)

In [376]:
# sum of alternate rows 
marks[::2].sum(axis=1)

array([ 84, 183])

In [377]:
a = np.random.randint(1,100,10)
a.mean(),a.std()

(np.float64(46.5), np.float64(31.87867625859016))

In [378]:
a = np.random.randint(1,10,5)
print(a)
print(a.cumsum())

[7 7 9 6 3]
[ 7 14 23 29 32]


In [379]:
a = np.random.randint(1,10,(3,3))
print(a)

[[3 7 8]
 [9 3 5]
 [5 3 6]]


In [380]:
a.cumsum(axis = 1)  # Row-wise cumulative sum

array([[ 3, 10, 18],
       [ 9, 12, 17],
       [ 5,  8, 14]])

In [381]:
a.cumsum(axis = 0)

array([[ 3,  7,  8],
       [12, 10, 13],
       [17, 13, 19]])

In [382]:
a = np.random.randint(1,10,10)
a

array([6, 3, 5, 7, 8, 5, 4, 7, 3, 7], dtype=int32)

#### argmax(), argmin()

In [383]:
a.argmax(), a.argmin()    # index for max and min values in the array 

(np.int64(4), np.int64(1))

In [384]:
a = np.array([5,3,10,2,1])
a.argsort()

array([4, 3, 1, 0, 2])

In [385]:
sa = a [ a.argsort() ]
sa

array([ 1,  2,  3,  5, 10])

In [387]:
sa.searchsorted(15)

np.int64(5)

In [388]:
l = a.tolist()

In [389]:
type(l)

list

#### Sorting 

In [390]:
a = np.array( (6,7,5,3,2))

In [392]:
sa = sorted(a, reverse=True)  # Python function 
print(sa)

[np.int64(7), np.int64(6), np.int64(5), np.int64(3), np.int64(2)]


In [393]:
a

array([6, 7, 5, 3, 2])

In [394]:
a.sort()  # Inplace sorting 

In [395]:
a

array([2, 3, 5, 6, 7])

#### 2D array

In [396]:
a = np.random.randint(1,10,(3,3))
a

array([[2, 6, 2],
       [6, 8, 2],
       [9, 7, 9]], dtype=int32)

In [397]:
a.sort() # Sort rows 
print(a)

[[2 2 6]
 [2 6 8]
 [7 9 9]]


In [398]:
a = np.random.randint(1,10,(3,3))
print(a)

[[9 3 6]
 [1 5 7]
 [9 1 4]]


In [400]:
a.sort(axis = 0)
print(a)

[[1 1 4]
 [9 3 6]
 [9 5 7]]


In [401]:
a = np.random.randint(1,10,(3,3))
print(a)
np.sort(a, axis=None)  # Sorting entire 2d array after flattening it 

[[3 9 9]
 [6 8 9]
 [1 7 7]]


array([1, 3, 6, 7, 7, 8, 9, 9, 9], dtype=int32)

In [402]:
a

array([[3, 9, 9],
       [6, 8, 9],
       [1, 7, 7]], dtype=int32)

In [403]:
np.sort(a)  # Row-wise sorting 

array([[3, 9, 9],
       [6, 8, 9],
       [1, 7, 7]], dtype=int32)

In [404]:
a = np.random.randint(1,10,(3,3))
print(a)

[[7 9 2]
 [3 7 5]
 [9 6 5]]


In [405]:
np.sort(a, axis=None).reshape((3,3))

array([[2, 3, 5],
       [5, 6, 7],
       [7, 9, 9]], dtype=int32)

### Copy vs. View 

In [171]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [172]:
b = a[5:]  # b is a View into a 
b

array([ 6,  7,  8,  9, 10])

In [173]:
b[0] = 20

In [174]:
b

array([20,  7,  8,  9, 10])

In [175]:
a

array([ 1,  2,  3,  4,  5, 20,  7,  8,  9, 10])

In [176]:
b[:] = 0

In [177]:
a

array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])

In [178]:
a[9] = 100
b

array([  0,   0,   0,   0, 100])

In [179]:
b[:2] = [10,20]
b,a

(array([ 10,  20,   0,   0, 100]),
 array([  1,   2,   3,   4,   5,  10,  20,   0,   0, 100]))

In [180]:
c = b[:3]

In [181]:
c[0] = 100

In [182]:
a

array([  1,   2,   3,   4,   5, 100,  20,   0,   0, 100])

In [183]:
a1 = np.arange(1,11)
a2 = a1.copy()
a2[0] = 1000
a1,a2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10]))

In [184]:
a = np.array((1,2,3))
b = a[:]
del a    # Delete original 
print(b)

[1 2 3]


#### Boolean indexing in copy vs. view

In [185]:
# Array of booleans  
a = np.array((1,2,3,4,5))
na = a[a > 3]  # You get a copy of a 
na [0] = 100
a, na

(array([1, 2, 3, 4, 5]), array([100,   5]))

In [186]:
# Array of indexes 
a = np.array((1,2,3,4,5))
na = a[[1,3]]  # You get a copy of a 
na[0] = 100
a, na

(array([1, 2, 3, 4, 5]), array([100,   4]))

### Universal Functions
These are functions in Numpy module

In [187]:
a = np.arange(1,10)
b = np.arange(11,20)
a + b

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [188]:
np.add(a,b)

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [189]:
np.lcm(10,5), np.gcd(10,30)

(np.int64(10), np.int64(10))

In [190]:
np.sqrt( [10,15,30,40])

array([3.16227766, 3.87298335, 5.47722558, 6.32455532])

In [191]:
np.sign(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

### Stacking and splitting 

In [192]:
a1 = np.arange(1,5).reshape(2,2)
a1

array([[1, 2],
       [3, 4]])

In [193]:
a2 = np.arange(10,16).reshape(2,3)
a2

array([[10, 11, 12],
       [13, 14, 15]])

In [194]:
np.hstack((a1,a2))

array([[ 1,  2, 10, 11, 12],
       [ 3,  4, 13, 14, 15]])

In [195]:
a2 = np.arange(10,14).reshape(2,2)
a2

array([[10, 11],
       [12, 13]])

In [196]:
np.vstack((a1,a2))

array([[ 1,  2],
       [ 3,  4],
       [10, 11],
       [12, 13]])

In [197]:
np.concatenate((a1,a2))   # Vertical stacking - defualt axis = 0 

array([[ 1,  2],
       [ 3,  4],
       [10, 11],
       [12, 13]])

In [198]:
np.concatenate((a1,a2), axis=1)  # Horizontal stacking 

array([[ 1,  2, 10, 11],
       [ 3,  4, 12, 13]])

In [199]:
a1 = np.random.randint(1,10,(2,2))
a2 =  np.random.randint(1,10,(3,2))
# np.hstack((a1,a2))
# np.vstack((a1,a2))

#### Splitting

In [200]:
a = np.arange(1,19).reshape(6,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [201]:
np.vsplit(a,2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])]

In [202]:
a1, a2 = np.vsplit(a,2) # unpacking 

In [203]:
a1.shape, a2.shape

((3, 3), (3, 3))

In [204]:
np.vsplit(a, (1, 4))   # Split at row 1 and row 4 

[array([[1, 2, 3]]),
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [205]:
np.vsplit(a, (4,))

[array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [206]:
np.hsplit(a, (2,))  

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14],
        [16, 17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [207]:
a1, a2, a3 = np.vsplit(a, (1,4))   # Unpacking 

In [208]:
a1.shape, a2.shape, a3.shape 

((1, 3), (3, 3), (2, 3))

In [209]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [210]:
a1, a2 = np.vsplit(a,2)

In [211]:
a1, a2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [212]:
a1[0,0] = 100

In [213]:
a

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18]])

### Reshaping array

In [214]:
a = np.arange(1,10)
b = a.reshape(3,3)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [215]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [216]:
b[0,0] = 100    # B is a view to A
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [217]:
c = np.reshape(a, (-1,3))  # decide the number of rows 
c

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [218]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [219]:
np.reshape(a, (3,3), order='F')  # column-wise 

array([[100,   4,   7],
       [  2,   5,   8],
       [  3,   6,   9]])

In [220]:
np.reshape(a, (3,3))   # C order, row-wise

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

#### ravel()

In [221]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [222]:
ar  = a.ravel()  # Returns a 1d array which is a view 
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [223]:
ar[0] = 10

In [224]:
a

array([[10,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

#### flatten()

In [225]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [226]:
fa = a.flatten()  # Copy 
fa

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [227]:
fa[0] = 1000
fa, a

(array([1000,    1,    2,    3,    4,    5,    6,    7,    8]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]))

In [228]:
a.flatten('F')  # Column-major - Fortran

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

#### reshape()

In [229]:
a = np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [230]:
a.transpose()

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [231]:
a.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

#### resize() - inplace resize

In [232]:
a = np.arange(20)
print(a)
a.resize(2,5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [233]:
a = np.arange(10)
print(a)
a.resize(5)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


### Linear Algebra

#### Transpose

In [234]:
a = np.arange(1,21).reshape(4,5)
print(a)
print(a.T)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [235]:
a = np.random.randint(1,10, (5,5))
a

array([[7, 7, 6, 2, 7],
       [9, 8, 1, 8, 8],
       [3, 1, 7, 8, 8],
       [5, 9, 6, 8, 1],
       [3, 1, 5, 8, 5]], dtype=int32)

In [236]:
np.linalg.inv(a)

array([[ 0.28108108, -0.06645469, -0.71096979, -0.17901431,  0.88616852],
       [-0.12972973,  0.08044515,  0.38696343,  0.16406995, -0.5990461 ],
       [ 0.12972973, -0.13926868, -0.09284579,  0.01240064,  0.1872814 ],
       [-0.11621622,  0.04387917,  0.02925278,  0.04403816,  0.03688394],
       [-0.08648649,  0.09284579,  0.39523052, -0.00826709, -0.4581876 ]])

In [237]:
a = np.random.randint(1,5,(3,4))
b = np.random.randint(1,5,(4,2))
a,b

(array([[3, 4, 4, 2],
        [2, 3, 1, 4],
        [3, 3, 3, 2]], dtype=int32),
 array([[2, 4],
        [4, 4],
        [1, 1],
        [3, 2]], dtype=int32))

In [238]:
a @ b   #  rows form a  X cols of b 

array([[32, 36],
       [29, 29],
       [27, 31]], dtype=int32)

In [239]:
a.dot(b)

array([[32, 36],
       [29, 29],
       [27, 31]], dtype=int32)

In [240]:
np.arange(1,10).reshape(3,3) * np.arange(1,10).reshape(3,3)    # Normal product (multiplication)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [241]:
np.arange(1,10).reshape(3,3) @ np.arange(1,10).reshape(3,3)  # Dot product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### Linear Regression with multiple variables using Linalge

In [242]:
X = np.array([[1,1000,2],[1,2000,3],[1,750,1]]) # 1,Size, No.bed rooms

In [243]:
X,X.shape

(array([[   1, 1000,    2],
        [   1, 2000,    3],
        [   1,  750,    1]]),
 (3, 3))

In [244]:
coef = np.array([2000000,5000,200000])  # Intercept and b1, b2 (Slope)
coef.shape

(3,)

In [245]:
y = X @ coef
y

array([ 7400000, 12600000,  5950000])

In [246]:
X.dot(coef)

array([ 7400000, 12600000,  5950000])

### Broadcasting

In [406]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [407]:
a + 10   # 10 is broadcast to array of 5 elements

array([10, 11, 12, 13, 14])

In [408]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [409]:
a + 10     # 10 is broadcast to (2,2)

array([[10, 11],
       [12, 13]])

In [410]:
a

array([[0, 1],
       [2, 3]])

In [411]:
a + np.array([1,2])

array([[1, 3],
       [3, 5]])

In [415]:
#a + np.array([2, 2, 3])

In [416]:
b = np.random.randint(1,5,(3,6))
c = np.random.randint(1,5,(3,1))

In [417]:
print(b)
print(c)

[[2 2 2 3 1 4]
 [1 3 4 1 1 2]
 [4 4 2 1 1 2]]
[[1]
 [2]
 [2]]


In [418]:
b + c  # c is broadcast to 6 cols 

array([[3, 3, 3, 4, 2, 5],
       [3, 5, 6, 3, 3, 4],
       [6, 6, 4, 3, 3, 4]], dtype=int32)

In [419]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [420]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [422]:
#a + b

In [423]:
a[:,:4] + b

array([[ 0,  2,  4,  6],
       [ 5,  7,  9, 11]])

In [425]:
a = np.arange(9)
b = np.arange(3)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8]
[0 1 2]


In [427]:
a.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [429]:
a.reshape((3,3)) + b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

## Image processing

In [436]:
import matplotlib.pyplot as plt
from scipy import misc

In [440]:
600 * 800 * 3

1440000

In [439]:
img = misc.face()
type(img), img.shape, img.size

AttributeError: module 'scipy.misc' has no attribute 'face'

In [ ]:
plt.imshow(img)

In [ ]:
img.dtype

In [ ]:
img[0,0]   # Colors at 0,0

In [ ]:
img[0,0,2]  # Blue at 0,0 

In [ ]:
img[-1,-1]   # Last pixel 

In [ ]:
newimg = img.copy()

In [ ]:
newimg[:100,:100,:] = [255,0,0]  # Red patch in upper left corner (100 x 100)

In [ ]:
plt.imshow(newimg)

In [ ]:
newimg[-100:,-100:,:] = [0,0,255]  # Blue patch at the bottom right corner 

In [ ]:
plt.imshow(newimg)

In [ ]:
face = img[200:500, 450:850]

In [ ]:
plt.imshow(face)

In [ ]:
face2 = img.copy()
f1, f2 = np.vsplit(face2, (600,))
plt.imshow(f1)

In [ ]:
plt.imshow(f2)

In [ ]:
plt.imshow(np.vstack((f1,f2)))

In [ ]:
(face2[:,:,2] == 0).sum()     # How many pixels have blue color set to zero

In [ ]:
(face2[:,:,0] > 200).sum()  # How many pixels have red > 200

In [ ]:
newimg = img.copy()
newimg[:,:,2] = 0    # Set blue part of image to 0
plt.imshow(newimg)

In [ ]:
gimg = misc.ascent()
gimg.shape

In [ ]:
gimg[0,0]

In [ ]:
plt.imshow(gimg)

In [ ]:
gimg.size

In [ ]:
(gimg > 200).sum()

In [ ]:
(gimg == 255).sum()

In [ ]:
plt.gray()
plt.imshow(gimg)